### ISSUE TITLE
phonegap build

### ISSUE THREAD

**Issue by kenjibizweb** [Tunts/WebIntent#3]
Hi.. I would like to use your webintent plugins with phonegap build but it seems like it can only be used in Cordova is it? Thanks

**Comment by wesleyakio** [comment]
Hi @kenjibizweb . It is already included in the build plugin list: https://build.phonegap.com/plugins/363.
I try to keep it updated there as well.

**Comment by kenjibizweb** [comment]
Hi... Thanks for replying. 

I was reading through on the webintent and were saying about the Intent Filter in AndroidManifest.Xml and I did trying in phonegap on the code below upon a button click but there is no response. And could you please show an example of like... I wants to share an image and text when I click on the phonegap button with other Android application. Usually it show "Share Via" and show a Share List

window.plugins.webintent.startActivity({
    action: window.plugins.webintent.ACTION_VIEW,
    url: 'http://www.google.com.sg'}, 
    function() {}, 
    function() {alert('Failed to open URL via Android Intent')};
);

**Comment by kenjibizweb** [comment]
Hi... Thanks for replying.

I was reading through on the webintent and were saying about the Intent
Filter in AndroidManifest.Xml and I did trying in phonegap on the code
below upon a button click but there is no response. And could you please
show an example of like... I wants to share an image and text when I click
on the phonegap button with other Android application. Usually it show
"Share Via" and show a Share List

window.plugins.webintent.startActivity({
action: window.plugins.webintent.ACTION_VIEW,
url: 'http://www.google.com.sg'},
function() {},
function() {alert('Failed to open URL via Android Intent')};
);

Thank you in advance.
