### ISSUE TITLE
Basic phonegap build setup

### ISSUE THREAD

**Issue by alscheuring** [Tunts/WebIntent#5]
Hi, I'd really like to use your plugin to launch apps from my Phonegap 3 app. I'm getting stuck though with the examples.

I've added the plugin in my config.xml like so:
<gap:plugin name="net.tunts.webintent" />

Added the plugin locally
phonegap plugin add https://github.com/Tunts/WebIntent.git

Copied the webintent.js file from the plugins www folder to my www folder and referenced it in index.html
    <script type="text/javascript" src="js/webintent.js"</script>

In index.html I have the following test. Am I messing up here? I get the failed alert when I click on the link.

```
    <a href='#' ontouchend="untappdTest()">UNTAPPD TEST</a>
```

<script>
    function untappdTest(){
  window.plugins.webintent.startActivity({
    action: WebIntent.ACTION_VIEW,
    url: 'tel:',
  }, function () {}, function () {
    alert('Failed to open URL via Android Intent');
  });   
        
    }
</script>

**Comment by wesleyakio** [comment]
Hello @alscheuring,
First, you should not need to copy the js file manually, Phonegap build will do that for you.
Second, could you please share the code for "untappdTest()".

Best

**Comment by wesleyakio** [comment]
No feedback from reporter. Unable to test further.
